import { Card, Dropdown } from "flowbite-react";
import { NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import Navigation from "../../components/Navigation";
import { NoteCard } from "../../components/NoteCard";
import useDarkMode from "../../utils/useDarkMode";
import { trpc } from "../_app";

const Notes: NextPage = () => {
  const [colorTheme, setTheme] = useDarkMode();
  
  const notes = trpc.note.getNotes.useQuery();
  
  const deleteNoteMutation = trpc.note.deleteNote.useMutation({
    onSuccess() {
      alert("OK")
    }
  });

  const deleteNote = (noteId: string) => {
    deleteNoteMutation.mutate({ noteId });
  }

  return (
    <>
        <Head>
            <title>Notes</title>
            <meta name="description" content="Generated by create-t3-app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className="dark:bg-black dark:text-white">
          <Navigation />

          <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
            <h1 className="text-5xl mb-4">Notes</h1>
            <div className="grid gap-3 pt-3 mt-3 text-center md:grid-cols-2 lg:w-2/3">
            {
            notes.data?.length ? (
            notes.data?.map((note, index) => 
              <Card>
                <div className="flex justify-items-stretch">
                  <div>
                    <h5 className="mb-1 text-xl font-medium text-gray-900 dark:text-white">{note.title}</h5>
                  </div>
                  <div className="justify-self-end">
                    <Dropdown inline={true} label="">
                      <Dropdown.Item>
                        <button onClick={() => deleteNote(note.id)}>Delete</button>
                      </Dropdown.Item>
                    </Dropdown>
                  </div>
                </div>
                <div className="flex flex-nowrap pb-10">
                  <span className="text-sm text-gray-500 dark:text-white">{note.body}</span>
                </div>
              </Card>
              )
            ) : ( <div>No notes yet.</div> )
            }
            </div>
          </main>
        </div>
    </>
  )
}

export default Notes;