import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { trpc } from "./_app";

const About: NextPage = () => {
    const technologyCards = trpc.example.getTechnologyCards.useQuery();

    return (
        <>
        <Head>
            <title>About</title>
            <meta name="description" content="Generated by create-t3-app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
          <h1 className="text-5xl mb-8">About</h1>
          <h1 className="text-2xl leading-normal font-extrabold text-gray-700">
              This is an example <span className="text-blue-600 sh">T3 Stack</span> note app created with <span className="text-blue-600 sh">create-t3-app</span>
          </h1>
          <p className="text-2xl text-gray-700">This stack uses:</p>
          <div className="grid gap-3 pt-3 mt-3 text-center md:grid-cols-2 lg:w-2/3">
            {technologyCards.data?.map((card) => 
              <TechnologyCard
                name={card.name}
                description={card.description}
                documentation={card.documentation}
              />
            )}
          </div>
          <nav className="flex justify-center space-x-4 space-x-4 mt-4">
          <Link href="/">
            <a className="border border-indigo-800 border-slate-300 hover:border-slate-400 px-3 py-2 text-slate-700 hover:bg-slate-100  hover:text-slate-900">
               Go Back
            </a>
          </Link>
          </nav>
        </main>
        </>
    )
}

export default About;

type TechnologyCardProps = {
    name: string;
    description: string;
    documentation: string;
  };
  
  const TechnologyCard = ({
    name,
    description,
    documentation,
  }: TechnologyCardProps) => {
    return (
      <section className="flex flex-col justify-center p-6 duration-500 border-2 border-gray-500 rounded shadow-xl motion-safe:hover:scale-105">
        <h2 className="text-lg text-gray-700">{name}</h2>
        <p className="text-sm text-gray-600">{description}</p>
        <a
          className="mt-3 text-sm underline text-violet-500 decoration-dotted underline-offset-2"
          href={documentation}
          target="_blank"
          rel="noreferrer"
        >
          Documentation
        </a>
      </section>
    );
  };