import type { NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import Navigation from "../components/Navigation";
import useDarkMode from "../utils/useDarkMode";
import { trpc } from "./_app";

const Home: NextPage = () => {
  const [colorTheme, setTheme] = useDarkMode();

  const { data: session } = useSession();
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  
  return (
    <>
      <Head>
        <title>T3 Stack Note App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="dark:bg-black dark:text-white">

      <Navigation />

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        
        <h1 className="text-5xl md:text-[4rem] leading-normal font-extrabold text-gray-700 dark:text-white mb-4">
          T3 Stack <span className="text-blue-600 sh">Note</span> App
        </h1>
        <button onClick={() => setTheme("dark")}>theme: dark</button>
        <button onClick={() => setTheme("light")}>theme: light</button>

        <div className="pt-6 text-2xl text-blue-500 flex justify-center items-center w-full">
          {hello.data ? <p>{hello.data}</p> : <p>Loading..</p>}
        </div>
      
      </main>
      </div>
    </>
  );
};

export default Home;
